# site settings
title: Tranquiloquence
subtitle: Rohit Prakash
email: rohitp934@gmail.com
description: I'm a budding Computer Scientist who is exploring the world on his own, trying to find out his inner passion.<br />I love writing, drawing, photographing and many more. Changing the world, one step at a time.
baseurl: "/tranquil" # the subpath of your site, e.g. /blog
url: "rohitp934.github.io" # the base hostname & protocol for your site
author: Rohit Prakash
city: Chennai
state: TN
country: India

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rohitp934
gitlab_url: #https://gitlab.com/u/andrewbanchich
googleplus_url: #https://plus.google.com/u/0/+AndrewBanchich
instagram_url: #https://instagram.com
linkedin_url: #https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Drakcarys

# build settings
markdown: kramdown

sass:
  style: compressed
